### PR TITLE
connects with rtracklayer Chain and liftOver to obtain SNP addresses from specified genome builds

### PR DESCRIPTION
**Pull request by vjcitn**
final section of vignette illustrates behavior of ncbi_snp_query2 when a chain parameter is supplied.  The chain object is in data folder, man page example includes the illustration.

### CODE REVIEW

**Comment by sckott** [comment]
thanks I'll have a look 

via #38

**Comment by vjcitn** [comment]
I noticed that TravisCI fails for lack of bioconductor packages like
GenomeInfoDb.  I only
import packages like this ... perhaps it needs an explicit Depends to
trigger installation?
Let me know what I must do to get this to proceed.

On Tue, Jan 24, 2017 at 3:07 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
You could add the bioc pkgs to the travis file https://docs.travis-ci.com/user/languages/r/

You added 8 new pkg dependencies - is there any way to achieve the same thing with fewer dependencies?

**Comment by vjcitn** [comment]
I can probably cut it to 4.  Is this an important consideration?  I will
drop
as many as I can before changing the travis list.

On Wed, Jan 25, 2017 at 3:30 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
I misspoke it was 7, not 8.  I generally want to keep dependencies as light as possible as it's easier to maintain this piece of software and more deps can lead to more installation problems for users. Essential pkgs you need for the core feature you're adding are important to have, but if others can be removed that's great.

**Comment by sckott** [comment]
any thoughts @vjcitn ?

**Pull request closed without merging**
