### PR TITLE
T71 revdep updated folder

### PR DESCRIPTION
**Pull request by jooolia**
## Description
Updated the revdep folder after running `revdepcheck::revdep_check(num_workers = 4, timeout = as.difftime(360,units = "mins"))`. All checks pass, however the folder is now much bigger than before. Previously it was 8.1mb and now my checks are at 82 mb! I'm not convinced that I actually want all of these files in the repository. What do you think @sinarueeger?

### CODE REVIEW

**Comment by sinarueeger** [comment]
I agree that we should not have unnecessary (large) files under version control. 
How about we copy the `revdep` folder structure from the master branch?

That would be: 
```
revdep
|-- checks.noindex
|-- library.noindex/rsnps
|-- README.md
|-- checks.rds
|-- data.sqlite
|-- problems.md
``` 
We could add all `revdep/library/*` and `revdep/checks/*` into the `.gitignore` file.

What do you think @jooolia?

**Comment by jooolia** [comment]
Hi @sinarueeger,
I like this idea of adding revdep/library/* and revdep/check/* to the .gitignore. I think that failures.md should also be added (and a bit surprised that it was not already in the repo, perhaps there were issues before that were deemed ok and thus it was not added so not to confuse others..?). 

I regenerated the folders "revdep/checks" and "revdep/library" but not with the ".noindex" suffix. I will look into why this is.

**Comment by sinarueeger** [comment]
Yes, I agree, `failures.md` should also go in there.

Let me know if you want me to re-run something.

**Comment by jooolia** [comment]
Hi @sinarueeger,
Just a quick one. I see that directories created on macs ("Darwin" OS) get the ".noindex" suffix. https://github.com/r-lib/revdepcheck/blob/9304386f8eec0e7bf7b91645e106b178d3b77dc8/R/dirs.R (line 44). So this explains the discrepancies but doesn't give a clear path forward. :( Do you think ropensci might have thoughts on this?

**Comment by sinarueeger** [comment]
Hi @jooolia, 
We could ask in the ropensci slack what people usually do. 
I looked into other ropensci packages, and `visdat` specifically excludes the `noindex` files in the [`.gitignore`](https://github.com/ropensci/visdat/blob/master/revdep/.gitignore) file:  

```
checks
library
checks.noindex
library.noindex
data.sqlite
*.html
*.cache.rds
```

That would change the folder structure proposed above to: 
```
revdep
|-- README.md
|-- checks.rds
|-- problems.md
```

Does this make sense?

**Comment by jooolia** [comment]
Hi @sinarueeger,
Yes that sounds good to me (with of course our friend failures.md) and thanks for looking. :) I will update either tonight or tomorrow morning.

**Comment by sinarueeger** [comment]
Of course, I added `failures.md` to my comment.

**Comment by jooolia** [comment]
Hi @sinarueeger ,
I have updated as discussed. Please have a look and let me know what you think.

**Comment by jooolia** [comment]
Hi @sinarueeger,
I made the update you suggested in PR 83 so it would be easier to see the new changes (as there are many files here). Is that ok? Thanks, Julia

**Pull request merged**
