### PR TITLE
Added check for http errors in variable dat in LDSearch. (Just could …

### PR DESCRIPTION
**Pull request by ramiromagno**
…not miss fixing issue 42)

### CODE REVIEW

**Comment by ramiromagno** [comment]
It is not passing LDSearch tests because of SNAP's issue (issue #42 ), not because of this patch...

**Comment by sckott** [comment]
@ramiromagno So this is for when the server does not return an error code (so `stop_for_status()` call misses it) - but there was actually a server error? 

Can you add a test for this if possible?  I don't know whether it's possible to purposefully trigger the error, but if so, please add a test for it.

**Comment by ramiromagno** [comment]
Indeed the server does not return an error. The webpage returned however reports an http error, which is a different thing. And that is why `stop_for_status()` misses it. Reproduce it with this:

```
http://archive.broadinstitute.org/mpg/snap/ldsearch.php?snpList=rs11776767&hapMapRelease=onekgpilot&hapMapPanel=CEU&RSquaredLimit=0.8&distanceLimit=500000&downloadType=file&includeQuerySnp=on&submit=search&columnList%5B%5D=GA
```

The check I suggested is just to make clear where the source of the error is coming from; in this case, SNAP itself, otherwise, it resurfaces later in the code, making users think that there is some problem with the package itself. So, as soon as SNAP corrects this issue, my patch will pass your tests. Then, if in the future, this happens again, my check should capture the error and fail somewhat more nicely than it does now.

**Comment by sckott** [comment]
@ramiromagno okay, thanks, looks good.

**Pull request merged**
