### PR TITLE
Updating NEWS

### PR DESCRIPTION
**Pull request by sinarueeger**
Started a new branch for updating NEWS. What else should we mention here?

I think its ok if we merge this and then add on the go.

## Related Issue
#86, #88, #102

### CODE REVIEW

**Comment by jooolia** [comment]
Hi @sinarueeger,
Cool to get started on this and I like the idea of adding incrementally to it. Would it make sense though to include these new changes with the previous changes we had made (e.g. in 0.3.2)? So we would have them all in one release? So perhaps instead of 0.3.2 we could use 0.4.0? (I will have to check the versioning advice again. :)). 
Thanks! Julia

**Comment by sinarueeger** [comment]
ok with
- version 0.4.0
- bundling news (since this is mainly for CRAN)

**Comment by jooolia** [comment]
Hi @sinarueeger,
Great! One final little question, on line 19 should we remove reference to `R/NCBI_snp_query2.R` and `R/ncbi_snp_summary.R`?
Thanks! Julia

**Comment by sinarueeger** [comment]
Good point @jooolia, done! Ok now?

**Pull request merged**
