### PR TITLE
Fixtypo + orchid/email address Sina

### PR DESCRIPTION
**Pull request by sinarueeger**
## Description
- Fixed typo in `R/NCBI_snp_query2.R` documentation
- Added Sina's ORCID and email address to `DESCRIPTION`

### CODE REVIEW

**Comment by sinarueeger** [comment]
Hi @jooolia, I forgot to make a PR for this branch. That's the typo I was talking about on Friday evening ;-).

**Comment by sinarueeger** [comment]
Good catch @jooolia!
Remember that I mention that I had accidentally deleted parts of an example because I thought I had copy-pasted it? 
This was this one. So I deleted it from the .R file, but not from the .Rd file. 
I have brought it back to the R file now.

**Comment by sinarueeger** [comment]
@jooolia I messed up the whole PR. Let me fix this from scratch. Can you delete this PR and I make a new one?

**Comment by jooolia** [comment]
Hi @sinarueeger,
Ok I will close this PR and look at the alternative. :)

**Comment by jooolia** [comment]
I will let you delete the fixtypo-orchid branch at your leisure. :)

**Pull request closed without merging**
