### PR TITLE
[obsolete] Support for additional allele frequencies frequencies (from different databases)

### LINKED ISSUE #97: Add support for different frequency databases to ncbi_snp_query_api()
As brought up in #92, it would be nice to add support and tests for databases other than gnoMaD when using ncbi_snp_query_api().

### PR DESCRIPTION
**Pull request by sinarueeger**
dbsnp offers a range of allele frequencies from different databases (gnomad, alspac, 1000 genomes etc). we have added them to the rsnps::ncbi_snp_query(x) output.

## Description
rsnps currently appends the allele frequency of gnomad to the ncbi_snp_query(x) output. 

with this change, these columns are kept (alleles + frequency). 

additionally there is a dataframe attached per row (in tibble fashion) that contains allele frequencies per SNP per database. 

## Related Issue
fix #97 

## Example

```
aa <- ncbi_snp_query(c("rs420358", "rs456"))
str(aa)

## Number of new allele frequencies for first SNP
dim(aa$maf_population[[1]]) ## 16 x 4

## allele frequencies per SNP for TOPMED study
sapply(aa$maf_population, function(df) df[df$study == "TOPMED", "MAF"])


```

### CODE REVIEW

**Comment by sinarueeger** [comment]
@jooolia I am not sure about the list structure (the `aa$maf_population[[1]]` bit) and if we can get rid of `[[1]]`.

**Comment by jooolia** [comment]
Hi @sinarueeger this looks good to me. So I guess the only potential issue would be if people had been using get_frequency() directly but that does not seem likely to me so I am happy if we merge this (to dev? unless there are good reasons for master).

**Comment by sinarueeger** [comment]
@jooolia i think opensnp needs to update their SSL certificate (notified them about it). 
I will knit the README and VIGNETTE once all the opensnp functions work again. 

Additionally, I noticed that the vignette/rsnp.Rmd was not dynamic (ie had the function output c+p into the document). I changed that to proper Rmd format.

**Comment by sinarueeger** [comment]
Hi @jooolia
- SSL stuff is working again! (solution was to add `CURL_SSL_BACKEND=secure-transport` as environment variable before loading `curl`)
- I knitted the README. 
- I changed the NEWS file slightly.

**Comment by jooolia** [comment]
Hi @sinarueeger,
can you update so that the PR is pointing to dev? Thanks!

**Comment by sinarueeger** [comment]
@jooolia done in #142

**Pull request closed without merging**
