### PR TITLE
update cran comments

### PR DESCRIPTION
**Pull request by sinarueeger**
Changed cran.comments a little bit. 

@jooolia can you run R CMD CHECK and verify that there this is true `0 errors | 0 warnings | 1 note`?

I have no space on my mac left and R CMD CHECK is not working.

### CODE REVIEW

**Comment by jooolia** [comment]
Hi @sinarueeger, 
I updated the ubuntu and mac versions. Does this look ok? R CMD CHECK has no notes, errors or warnings on my machine.

**Comment by sinarueeger** [comment]
Great! Could you replace `1 note` with `0 notes` then?

**Comment by sinarueeger** [comment]
I also get 
image

**Comment by sinarueeger** [comment]
@jooolia , ok to merge this?

**Comment by jooolia** [comment]
Hi @sinarueeger , I am a bit nervous to remove the 1 Note as we still get the note about the maintainer on a few of the systems. What do you think about keeping it as 0 errors 0 warnings and 1 notes? This file is new to me, but I think if we could be as conservative as possible it would be good. 

From http://r-pkgs.had.co.nz/release.html

> Check results: I always state that there were no errors or warnings. Any NOTEs go in a bulleted list. For each NOTE, I include the message from R CMD check and a brief description of why I think it’s OK. If there were no NOTEs, I’d say “There were no ERRORs, WARNINGs or NOTEs”

**Comment by sinarueeger** [comment]
Sure, thats a good point. I reverted my changes.

**Pull request merged**
