### PR TITLE
Added the use of Rtools to appveyor yaml 

### LINKED ISSUE #81: Dependency mime failing in windows CI checks
CI checks on the "windows" machine are failing due to the package mime not being able to be installed. 

https://ci.appveyor.com/project/sckott/rsnps/builds/25215851

<summary><strong>From line 438</strong></summary>

```r
/bin/sh: c:/Rtools/mingw_32/bin/gcc: No such file or directory
make: *** [init.o] Error 127
ERROR: compilation failed for package 'mime'
* removing 'c:/RLibrary/mime'
Error in i.p(...) : 
  (converted from warning) installation of package 'mime' had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
Command exited with code 1
```

How to fix?

### PR DESCRIPTION
**Pull request by jooolia**
Added the use of Rtools to appveyor yaml so that compiled package mime can be properly built.  As described by @sinarueeger, Rtools is needed for packages need to be compiled on Windows OS. 

Related Issue
Fix  #81

### CODE REVIEW

**Comment by sinarueeger** [comment]
@jooolia, do you have a clue why this travis-ci is failing? It seems like `R CMD check log logs` is failing. 
The your change in `appveyor.yml` is identical to the change I made in #82. 
So I am tempted to just merge the PR. 
What do you think?

**Comment by jooolia** [comment]
Hi @sinarueeger,

Ok the error in Travis CI was due to the unit test failing. I had created the branch from master and thus it doesn't have your fix. I will merge in dev and it should then pass.

**Comment by jooolia** [comment]
Ok all passed! Sorry for the mix-up @sinarueeger (not sure why I had branched from master!).

**Comment by sinarueeger** [comment]
No problem @jooolia!

**Pull request merged**
