### PR TITLE
T123 GitHub actions

### PR DESCRIPTION
**Pull request by jooolia**
Playing around with the basic github actions by running `usethis::use_github_action_check_standard()`

### CODE REVIEW

**Comment by jooolia** [comment]
Hi @sinarueeger ,
I was just playing around with this to try removing the travis CI and replacing it with the github actions. What do you think? I am sure it could be improved a bit.

**Comment by sinarueeger** [comment]
Hi @jooolia, 
Thanks for tackling this! 
I just started using gh actions today for a python project. Looking through the github/workflow/yml file, it looks ok for me and the tests pass, and we have the badges updated - so thats the minimum we need. 

Did you use these commands? https://ropenscilabs.github.io/actions_sandbox/#usethis-wrappers

**Comment by jooolia** [comment]
Hi @sinarueeger,
Ok great. If you are ok we could merge this into dev. Then we could merge into master so that master would be covered by Github actions and it would remove our use of TravisCI. I can open another PR for this merge afterward.

**Comment by sinarueeger** [comment]
Thanks - that sounds good!

**Pull request merged**
